### PR TITLE
”async/await” more aggressive. + more

### PR DESCRIPTION
**Pull request by isnot**
Hello.

PullRequest the fix I made.
If you like it, merge it.

- Changed to use async / await more aggressively.
- TypeError occurred in matchAll (), so I modified the relevant part.
- Fix broken string during parse song if contain white space.
- Throw error if invalid params in parseKvp or parseGreeting. (for type consistency)
- feauture: new procedure 'query'

Thank you for the wonderful product.

### CODE REVIEW

**Comment by RomanBurunkov** [comment]
Hi, sorry.

Looks I've missed your update.
Thank you will be able review that a bit later.

**Comment by RomanBurunkov** [comment]
Hi @isnot 

Could you please elaborate the issue with TypeError occurred in matchAll.
In which conditions that happens?

I've checked your change and it doesn't look good for me:

```js
const matches = [...message.match(/(?:changed:\s*)(.*)/g)];
```

My questions about it are:

- Match doesn't catch the groups with a /g flag so do we really need them in regex?
- If there are no match it returns null so with spread operator we got an array with a one element like [null] with all consequences
 - Since no regex groups you have to .substring(9) but in case you have null in result array you will get an error.

About more aggressive async/await. Wrapping simple methods like delete or methods which doesn't have any async ops. in async/await you are creating promise inside a promise which just an overhead.

E.g.

```js
  async add(name) {
    return await this.command('add', name);
  }
```

`this.command('add', name)` is already a promise, but you created one more with `async add` method and wrapping one into another.

**Comment by isnot** [comment]
Hi @RomanBurunkov 
Thank you for your reply and review of this PR.

In your suggestion, I found my code to be poor.
I'm trying to brush up soon.
Therefore, we will temporarily suspend this PR until the work is completed.

**Comment by RomanBurunkov** [comment]
Looks that is not actual PR. Closing.

**Pull request closed without merging**
